'''text1
CRYPTANALYSIS IN RECENT PUBLICATIONS ALSO CRYPTANALYSIS REFERS IN THE ORIGINAL SENSE TO THE STUDY OF METHODS AND TECHNIQUES TO OBTAIN INFORMATION FROM SEALED TEXTS THIS INFORMATION CAN BE BOTH THE KEY USED AND THE ORIGINAL TEXT NOWADAYS, THE TERM CRYPTANALYSIS MORE GENERALLY REFERS TO THE ANALYSIS OF CRYPTOGRAPHIC METHODS NOT ONLY FOR CLOSURE WITH THE AIM OF EITHER BREAKING THEM IE ABOLISHING THEIR PROTECTIVE FUNCTION OR  OR TO PROVE AND QUANTIFY THEIR SECURITY CRYPTANALYSIS IS THUS THE COUNTERPART TO CRYPTOGRAPHY BOTH ARE SUBFIELDS OF CRYPTOLOGY
'''
'''text2
DIE KRYPTOANALYSE IN NEUEREN PUBLIKATIONEN AUCH KRYPTANALYSE BEZEICHNET IM URSPRUNGLICHEN SINNE DAS STUDIUM VON METHODEN UND TECHNIKEN UM INFORMATIONEN AUS VERSCHLUSSELTEN TEXTEN ZU GEWINNEN DIESE INFORMATIONEN KONNEN SOWOHL DER VERWENDETE SCHLUSSEL ALS AUCH DER ORIGINALTEXT SEIN HEUTZUTAGE BEZEICHNET DER BEGRIFF KRYPTOANALYSE ALLGEMEINER DIE ANALYSE VON KRYPTOGRAPHISCHEN VERFAHREN NICHT NUR ZUR VERSCHLUSSELUNG MIT DEM ZIEL DIESE ENTWEDER ZU BRECHEN D H IHRE SCHUTZFUNKTION AUFZUHEBEN BZW ZU UMGEHEN ODER IHRE SICHERHEIT NACHZUWEISEN UND ZU QUANTIFIZIEREN KRYPTOANALYSE IST DAMIT DAS GEGENSTUCK ZUR KRYPTOGRAPHIE BEIDE SIND TEILGEBIETE DER KRYPTOLOGIE
'''
'''text3
MVWZXYXEJIWGCML BIAORRZYZVMAKXGYRQKPQYGPITRKRYVCQSWPOJCBWGXXFOSPSKGXEJCILCIRYXFOWREHWYJKOXFYHQKRBDIARRGAYCCXMYFRKMLSRDYVKKXGYRDBSKCIYVIBDIVDWRRMQSRDYVKKXGYRAKRZO FMDLRRIIOCSCIBKRBDLCYVGQMLKPROBRXSUKHYIW, RRIROVKMVWZXYXEJIWGCQMBIEORCBEJVCPOJCBWRYXFOELKPWCMQYJABCNDSEBENRMAWIRRSBCRMDSLVCDYVAVSQEVCGMRRXFOEGWSDOMRRIPLVCKOGXKRRIKS IYLSJSWFSREDLCSVNBSROGRSZCPYLMXGYRMB SPDS NBSTOELNUSKRRSJWDLCSVQOGSBMRIGPITRKRYVCQSWGCXFEWRRIAYYLDIPZEPDXMMVWZXMQVYZLWLSRREPOWSLJGOPBCSDMVWZXMVSEI
'''
'''text4
FUBSWDQDOBVLV LQUHFHQWSXEOLFDWLRQVDOVRFUBSWDQDOBVLVUHIHUVLQWKHRULJLQDOVHQVHWRWKHVWXGBRIPHWKRGVDQGWHFKQLTXHVWRREWDLQLQIRUPDWLRQIURPVHDOHGWHAWVWKLVLQIRUPDWLRQFDQEH ERWKWKHNHBXVHGDQGWKHRULJLQDOWHAWQRZDGDBV, WKHWHUP FUBSWDQDOBVLVPRUHJHQHUDOOBUHIHUVWRWKHDQDOBVLVRIFUBSWRJUDSKLFPHWKRGVQRWRQOBIRUFORVXUHZLWKWKHDLPRIHLWKHUEUHDNLQJWKHPL H DEROLVKLQJWKHLUSURWHFWLYHIXQFWLRQRU RUWRSURYHDQGTXDQWLIBWKHLUVHFXULWBFUBSWDQDOBVLV LV WKXVWKHFRXQWHUSDUWWRFUBSWRJUDSKBERWKDUH VXEILHOGVRIFUBSWRORJB
'''
import collections

cin=input()

elements_count=collections.Counter(cin)
N=0
f=0

for key,value in elements_count.items():
    if key==' ' or key==',' or key=='.':
        continue
    f+=(value*(value-1))
    N+=value

print(f/(N*(N-1)))